/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create User */
        post: operations["create_user_user_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_user__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{user_id}/upload-homework/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Homework */
        post: operations["upload_homework_user__user_id__upload_homework__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/homework-assistant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Homework Assistance Run */
        post: operations["trigger_homework_assistance_run_homework_assistant_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/homework-assistant/{homework_assistance_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Homework Assistance Run State */
        get: operations["get_homework_assistance_run_state_homework_assistant__homework_assistance_run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/homework-assistant/chat/{homework_assistance_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_homework_assistant_chat__homework_assistance_run_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/homework-assistant/status/{homework_assistance_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Homework Assistance Run Status */
        get: operations["get_homework_assistance_run_status_homework_assistant_status__homework_assistance_run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/homework-assistant/run/{homework_assistance_run_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Homework Assistance Run Tasks */
        get: operations["get_homework_assistance_run_tasks_homework_assistant_run__homework_assistance_run_id__tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_homework_user__user_id__upload_homework__post */
        Body_upload_homework_user__user_id__upload_homework__post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** CreateHomeworkAssistantRunRequest */
        CreateHomeworkAssistantRunRequest: {
            /** User Id */
            user_id: string;
            /** File Id */
            file_id: string;
        };
        /** CreateHomeworkAssistantRunResponse */
        CreateHomeworkAssistantRunResponse: {
            /** Homework Assistance Run Id */
            homework_assistance_run_id: string;
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            user: components["schemas"]["UserModel"];
        };
        /** CreateUserResponse */
        CreateUserResponse: {
            user: components["schemas"]["UserWithIdModel"];
        };
        /** GetHomeworkAssistanceRunStatusResponse */
        GetHomeworkAssistanceRunStatusResponse: {
            /** Homework Assistance Run Id */
            homework_assistance_run_id: string;
            /** Step States */
            step_states: {
                [key: string]: unknown;
            }[];
        };
        /** GetHomeworkAssistanceRunTasksResponse */
        GetHomeworkAssistanceRunTasksResponse: {
            /** Homework Assistance Run Id */
            homework_assistance_run_id: string;
            /** Tasks */
            tasks: components["schemas"]["TaskResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HomeworkAssistanceRunState
         * @enum {string}
         */
        HomeworkAssistanceRunState: "PENDING" | "STARTED" | "SUCCEEDED" | "FAILED";
        /** HomeworkAssistanceRunStatus */
        HomeworkAssistanceRunStatus: {
            /** Homework Assistance Run Id */
            homework_assistance_run_id: string;
            /** Labels */
            labels: string[];
            state: components["schemas"]["HomeworkAssistanceRunState"];
            /** Explanation */
            explanation: string | null;
        };
        /** Message */
        Message: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "system" | "assistant";
            /** Content */
            content: string;
        };
        /** TaskResponse */
        TaskResponse: {
            /** Id */
            id: string;
            /** Key */
            key: string;
            /** Description */
            description: string;
            /** Concepts */
            concepts: string[];
        };
        /** UserModel */
        UserModel: {
            /** Auth User Id */
            auth_user_id: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /** UserWithIdModel */
        UserWithIdModel: {
            /** Id */
            id: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_user_user_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_user__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserWithIdModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_homework_user__user_id__upload_homework__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_homework_user__user_id__upload_homework__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateHomeworkAssistantRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_homework_assistance_run_homework_assistant_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHomeworkAssistantRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateHomeworkAssistantRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_homework_assistance_run_state_homework_assistant__homework_assistance_run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                homework_assistance_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeworkAssistanceRunStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_homework_assistant_chat__homework_assistance_run_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                homework_assistance_run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Message"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_homework_assistance_run_status_homework_assistant_status__homework_assistance_run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                homework_assistance_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetHomeworkAssistanceRunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_homework_assistance_run_tasks_homework_assistant_run__homework_assistance_run_id__tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                homework_assistance_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetHomeworkAssistanceRunTasksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
