<template>
  <PageWrapper title="Homework Assistant">
    <transition
      @before-leave="beforeLeave"
      @leave="leave"
      appear
    >
      <Card v-if="!fileUploaded" class="max-w-1/2 overflow-hidden">
        <CardHeader>
          <CardTitle>AI Homework Assistant</CardTitle>
          <CardDescription>
            Upload homework to get help from our AI homework assistant.
          </CardDescription>
        </CardHeader>
        <CardContent>
          Our artificial intelligence assistant will analyze the provided
          homework and offer assistance in understanding and solving the task.
        </CardContent>
        <CardFooter>
          <div class="grid w-full max-w-sm items-center gap-1.5">
            <Label for="file">File</Label>
            <Input id="file" type="file">Upload files</Input>
          </div>
        </CardFooter>
      </Card>
    </transition>
    <div class="flex flex-col overflow-hidden space-y-4">
      <!-- Explanation Section -->
      <Card class="h-full flex flex-col ">
        <CardHeader>
          <CardTitle>Explanation</CardTitle>
          <CardDescription>
            Below you can see a simple explanation of the assignment generated by our AI.
          </CardDescription>
        </CardHeader>
        <CardContent class="flex-1 flex flex-col">
          <MarkdownComponent :content="markdown"/>
          <div class="flex flex-col flex-1 bg-white dark:bg-gray-900 rounded-lg ">
            <!-- Chat Messages -->
            <div
              ref="container"
              class="flex-1 overflow-y-auto space-y-4 px-4 pt-4"
            >
              <div
                v-for="(msg, i) in messages"
                :key="i"
                class="flex items-start"
                :class="msg.from === 'user' ? 'justify-end' : 'justify-start'"
              >
                <div
                  class="max-w-[80%] py-2 px-4 rounded-xl prose dark:prose-invert"
                  :class="msg.from === 'user'
                ? 'bg-blue-600 text-white rounded-br-none'
                : 'dark:bg-gray-800 text-gray-900 dark:text-gray-100 rounded-bl-none'"
                >
                  <MarkdownComponent :content="msg.content" />
                </div>
              </div>

              <!-- Typing Indicator -->
              <div v-if="loading" class="flex items-center">
                <div class="flex space-x-1">
                  <span class="w-2 h-2 bg-gray-400 dark:bg-gray-600 rounded-full animate-bounce-delay-0"></span>
                  <span class="w-2 h-2 bg-gray-400 dark:bg-gray-600 rounded-full animate-bounce-delay-200"></span>
                  <span class="w-2 h-2 bg-gray-400 dark:bg-gray-600 rounded-full animate-bounce-delay-400"></span>
                </div>
              </div>
            </div>

            <div class="-mx-6 -mb-6 mt-4 rounded-lg overflow-hidden">
            <!-- Input Area -->
            <div class="px-4 py-3 border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800 flex items-center space-x-2">
          <Textarea
            v-model="draft"
            placeholder="Type your message..."
            class="flex-1 resize-none"
            rows="1"
            @keydown.enter.stop.prevent="sendMessage"
            @input="autoResize"
          />
              <Button :disabled="!draft || loading" @click="sendMessage">
                Send
              </Button>
              <Button v-if="loading" variant="outline" size="sm" class="text-red-500" @click="stopGeneration">
                Stop
              </Button>
            </div>
          </div>
          </div>
        </CardContent>
      </Card>
    </div>

      <!-- Chat Section -->
  </PageWrapper>
</template>

<script setup lang="ts">
import { ref, onUpdated, nextTick } from 'vue'
import { Textarea } from '@/components/ui/textarea'
import { Button } from '@/components/ui/button'
import MarkdownComponent from '~/components/MarkdownComponent.vue'
import { useRuntimeConfig } from '#imports'


const fileUploaded = ref(false)

const markdown = `**Homework Assignment Explanation:**
The task is to calculate the total volume of a building with given side lengths of **4 meters (m)**, **10 meters (m)**, and **3 meters (m)**.

### **What to Do?**
1. **Understand the shape**: The building is assumed to be a rectangular prism (a box-shaped structure), as three distinct side lengths are provided.
2. **Use the formula for volume**:
   $$
   \\text{Volume} = \\text{Length} \\times \\text{Width} \\times \\text{Height}
   $$
3. **Multiply the given dimensions**:
   $$
   4\\, \\text{m} \\times 10\\, \\text{m} \\times 3\\, \\text{m} = 120\\, \\text{m}^3
   $$

### **Key Concepts to Understand**
1. **Volume of a rectangular prism**: Recognize that volume measures 3D space and requires multiplying all three dimensions.
2. **Units**: Ensure all measurements are in the same unit (meters here) and that the result is in cubic meters (m³).
3. **Application to real-world structures**: Relate abstract volume calculations to practical scenarios like buildings.

**Final Answer**:
The total volume of the building is **120 m³**.`

interface Message {
  from: 'user' | 'assistant'
  content: string
}

const messages = ref<Message[]>([])
const draft = ref('')
const loading = ref(false)
let controller: AbortController | null = null
const container = ref<HTMLElement | null>(null)

function autoResize(event: Event) {
  const el = event.target as HTMLTextAreaElement
  el.style.height = 'auto'
  el.style.height = el.scrollHeight + 'px'
}

async function sendMessage() {
  const text = draft.value.trim()
  if (!text) return
  messages.value.push({ from: 'user', content: text })
  draft.value = ''
  loading.value = true

  controller = new AbortController()
  const charDelay = 30
  let assistantContent = ''

  const baseUrl = useRuntimeConfig().public.apiBase
  const runId = 'your-homework-run-id' // TODO: inject this properly

  const jsonMessages = JSON.stringify(messages.value.map(m => ({ role: m.from, content: m.content })))

  try {
    const response = await fetch(`${baseUrl}/homework-assistant/chat/${runId}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: jsonMessages,
      signal: controller.signal,
    })

    if (!response.ok || !response.body) throw new Error('Stream failed')

    messages.value.push({ from: 'assistant', content: '' })
    const msgIndex = messages.value.length - 1

    const reader = response.body.getReader()
    const decoder = new TextDecoder()

    while (true) {
      const { value, done } = await reader.read()
      if (done) break
      const chunk = decoder.decode(value)
      for (const char of chunk) {
        assistantContent += char
        messages.value[msgIndex].content = assistantContent
        await new Promise(resolve => setTimeout(resolve,0))
      }
    }

  } catch (e) {
    console.error(e)
    messages.value.push({ from: 'assistant', content: '[Error during response streaming]' })
  } finally {
    loading.value = false
    controller = null
  }
}

function stopGeneration() {
  if (controller) controller.abort()
}

onUpdated(async () => {
  await nextTick()
  if (container.value) {
    container.value.scrollTop = container.value.scrollHeight
  }
})

</script>

<style scoped>
@keyframes bounce-delay {
  0%, 80%, 100% { transform: translateY(0); }
  40% { transform: translateY(-4px); }
}
.animate-bounce-delay-0 { animation: bounce-delay 1s infinite; }
.animate-bounce-delay-200 { animation: bounce-delay 1s infinite 0.2s; }
.animate-bounce-delay-400 { animation: bounce-delay 1s infinite 0.4s; }

.flex-1::-webkit-scrollbar { width: 6px; }
.flex-1::-webkit-scrollbar-thumb { background-color: rgba(100,100,100,0.4); border-radius: 3px; }
</style>
